on: [push]
jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    name: JMeter Test Execution
    steps:      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create reports directory
        run: mkdir reports
        
      - name: Run JMeter Tests
        uses: ./
        with:
          test-plan-path: ./TestPlans/S01_SimpleExample/S01_SimpleExample.jmx
          args: "-e -o ./reports/html/"
          
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: result.jtl

      - name: Upload Html Reports
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-reports
          path: reports          
